version: '3.6'

services:
  postgres:
    image: crpi-p29gej7egb3wfdey.cn-beijing.personal.cr.aliyuncs.com/hasura-deployer/postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    networks:
      - hasura-network

volumes:
  db_data:

networks:
  hasura-network:
    external: true
